[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
nftoken = "nftokf9qcHSYkVSP3P2gUMmV6d4AwjMueXgUu43HyLL"

[scripts]
test = "pnpm --filter program-tests exec jest"
