[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
nftoken = "nf4i4ZyQcYa3KbRnQDzBAncVpLJtS99aMEbjU2PwyKs"

[scripts]
test = "pnpm --filter program-tests exec jest"
