// IANA Timezones
// From https://www.iana.org/time-zones -> zone1970.tab
export const TIMEZONES = [
  "Africa/Abidjan",
  "Africa/Algiers",
  "Africa/Bissau",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/El_Aaiun",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Khartoum",
  "Africa/Lagos",
  "Africa/Maputo",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Sao_Tome",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Araguaina",
  "America/Argentina/Buenos_Aires",
  "America/Argentina/Catamarca",
  "America/Argentina/Cordoba",
  "America/Argentina/Jujuy",
  "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Asuncion",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Cayenne",
  "America/Chicago",
  "America/Chihuahua",
  "America/Costa_Rica",
  "America/Cuiaba",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Fort_Nelson",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Indianapolis",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Juneau",
  "America/Kentucky/Louisville",
  "America/Kentucky/Monticello",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Nuuk",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Punta_Arenas",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Sitka",
  "America/St_Johns",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Toronto",
  "America/Vancouver",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/Troll",
  "Antarctica/Vostok",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Atyrau",
  "Asia/Baghdad",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Chita",
  "Asia/Choibalsan",
  "Asia/Colombo",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Famagusta",
  "Asia/Gaza",
  "Asia/Hebron",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Kathmandu",
  "Asia/Khandyga",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qostanay",
  "Asia/Qyzylorda",
  "Asia/Riyadh",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Srednekolymsk",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Tomsk",
  "Asia/Ulaanbaatar",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yangon",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faroe",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/Stanley",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/Perth",
  "Australia/Sydney",
  "Etc/GMT",
  "Etc/GMT+1",
  "Etc/GMT+10",
  "Etc/GMT+11",
  "Etc/GMT+12",
  "Etc/GMT+2",
  "Etc/GMT+3",
  "Etc/GMT+4",
  "Etc/GMT+5",
  "Etc/GMT+6",
  "Etc/GMT+7",
  "Etc/GMT+8",
  "Etc/GMT+9",
  "Etc/GMT-1",
  "Etc/GMT-10",
  "Etc/GMT-11",
  "Etc/GMT-12",
  "Etc/GMT-13",
  "Etc/GMT-14",
  "Etc/GMT-2",
  "Etc/GMT-3",
  "Etc/GMT-4",
  "Etc/GMT-5",
  "Etc/GMT-6",
  "Etc/GMT-7",
  "Etc/GMT-8",
  "Etc/GMT-9",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Athens",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Helsinki",
  "Europe/Istanbul",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Lisbon",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/Saratov",
  "Europe/Simferopol",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Ulyanovsk",
  "Europe/Uzhgorod",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Reunion",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Chuuk",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Enderbury",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Wake",
  "Pacific/Wallis",
  "UTC",
] as const;

/**
 * This was computed by running https://gist.github.com/vpontis/3addd855fe5deadc95b031cc7b1f8022
 */
export const TZ_TO_PLACE: Record<typeof TIMEZONES[number], string> = {
  "Africa/Abidjan": "Greenwich Mean Time - Abidjan",
  "Africa/Algiers": "Central European Standard Time - Algiers",
  "Africa/Bissau": "Greenwich Mean Time - Bissau",
  "Africa/Cairo": "Eastern European Standard Time - Cairo",
  "Africa/Casablanca": "Morocco Time - Casablanca",
  "Africa/Ceuta": "Central European Time - Ceuta",
  "Africa/El_Aaiun": "Western Sahara Time - El Aaiun",
  "Africa/Johannesburg": "South Africa Standard Time - Johannesburg",
  "Africa/Juba": "Central Africa Time - Juba",
  "Africa/Khartoum": "Central Africa Time - Khartoum",
  "Africa/Lagos": "West Africa Standard Time - Lagos",
  "Africa/Maputo": "Central Africa Time - Maputo",
  "Africa/Monrovia": "Greenwich Mean Time - Monrovia",
  "Africa/Nairobi": "East Africa Time - Nairobi",
  "Africa/Ndjamena": "West Africa Standard Time - Ndjamena",
  "Africa/Sao_Tome": "Greenwich Mean Time - Sao Tome",
  "Africa/Tripoli": "Eastern European Standard Time - Tripoli",
  "Africa/Tunis": "Central European Standard Time - Tunis",
  "Africa/Windhoek": "Central Africa Time - Windhoek",
  "America/Adak": "Hawaii-Aleutian Time (Adak) - Adak",
  "America/Anchorage": "Alaska Time - Anchorage",
  "America/Araguaina": "Brasilia Standard Time - Araguaina",
  "America/Argentina/Buenos_Aires":
    "Argentina Standard Time - Buenos Aires, Argentina",
  "America/Argentina/Catamarca":
    "Argentina Standard Time - Catamarca, Argentina",
  "America/Argentina/Cordoba": "Argentina Standard Time - Cordoba, Argentina",
  "America/Argentina/Jujuy": "Argentina Standard Time - Jujuy, Argentina",
  "America/Argentina/La_Rioja": "Argentina Standard Time - La Rioja, Argentina",
  "America/Argentina/Mendoza": "Argentina Standard Time - Mendoza, Argentina",
  "America/Argentina/Rio_Gallegos":
    "Argentina Standard Time - Rio Gallegos, Argentina",
  "America/Argentina/Salta": "Argentina Standard Time - Salta, Argentina",
  "America/Argentina/San_Juan": "Argentina Standard Time - San Juan, Argentina",
  "America/Argentina/San_Luis": "Argentina Standard Time - San Luis, Argentina",
  "America/Argentina/Tucuman": "Argentina Standard Time - Tucuman, Argentina",
  "America/Argentina/Ushuaia": "Argentina Standard Time - Ushuaia, Argentina",
  "America/Asuncion": "Paraguay Time - Asuncion",
  "America/Bahia": "Brasilia Standard Time - Bahia",
  "America/Bahia_Banderas": "Central Time - Bahia Banderas",
  "America/Barbados": "Atlantic Standard Time - Barbados",
  "America/Belem": "Brasilia Standard Time - Belem",
  "America/Belize": "Central Standard Time - Belize",
  "America/Boa_Vista": "Amazon Standard Time - Boa Vista",
  "America/Bogota": "Colombia Standard Time - Bogota",
  "America/Boise": "Mountain Time - Boise",
  "America/Cambridge_Bay": "Mountain Time - Cambridge Bay",
  "America/Campo_Grande": "Amazon Standard Time - Campo Grande",
  "America/Cancun": "Eastern Standard Time - Cancun",
  "America/Caracas": "Venezuela Time - Caracas",
  "America/Cayenne": "French Guiana Time - Cayenne",
  "America/Chicago": "Central Time - Chicago",
  "America/Chihuahua": "Mexican Pacific Time - Chihuahua",
  "America/Costa_Rica": "Central Standard Time - Costa Rica",
  "America/Cuiaba": "Amazon Standard Time - Cuiaba",
  "America/Danmarkshavn": "Greenwich Mean Time - Danmarkshavn",
  "America/Dawson": "Mountain Standard Time - Dawson",
  "America/Dawson_Creek": "Mountain Standard Time - Dawson Creek",
  "America/Denver": "Mountain Time - Denver",
  "America/Detroit": "Eastern Time - Detroit",
  "America/Edmonton": "Mountain Time - Edmonton",
  "America/Eirunepe": "Acre Standard Time - Eirunepe",
  "America/El_Salvador": "Central Standard Time - El Salvador",
  "America/Fort_Nelson": "Mountain Standard Time - Fort Nelson",
  "America/Fortaleza": "Brasilia Standard Time - Fortaleza",
  "America/Glace_Bay": "Atlantic Time - Glace Bay",
  "America/Goose_Bay": "Atlantic Time - Goose Bay",
  "America/Grand_Turk": "Eastern Time - Grand Turk",
  "America/Guatemala": "Central Standard Time - Guatemala",
  "America/Guayaquil": "Ecuador Time - Guayaquil",
  "America/Guyana": "Guyana Time - Guyana",
  "America/Halifax": "Atlantic Time - Halifax",
  "America/Havana": "Cuba Time - Havana",
  "America/Hermosillo": "Mexican Pacific Standard Time - Hermosillo",
  "America/Indiana/Indianapolis": "Eastern Time - Indianapolis, Indiana",
  "America/Indiana/Knox": "Central Time - Knox, Indiana",
  "America/Indiana/Marengo": "Eastern Time - Marengo, Indiana",
  "America/Indiana/Petersburg": "Eastern Time - Petersburg, Indiana",
  "America/Indiana/Tell_City": "Central Time - Tell City, Indiana",
  "America/Indiana/Vevay": "Eastern Time - Vevay, Indiana",
  "America/Indiana/Vincennes": "Eastern Time - Vincennes, Indiana",
  "America/Indiana/Winamac": "Eastern Time - Winamac, Indiana",
  "America/Inuvik": "Mountain Time - Inuvik",
  "America/Iqaluit": "Eastern Time - Iqaluit",
  "America/Jamaica": "Eastern Standard Time - Jamaica",
  "America/Juneau": "Alaska Time - Juneau",
  "America/Kentucky/Louisville": "Eastern Time - Louisville, Kentucky",
  "America/Kentucky/Monticello": "Eastern Time - Monticello, Kentucky",
  "America/La_Paz": "Bolivia Time - La Paz",
  "America/Lima": "Peru Standard Time - Lima",
  "America/Los_Angeles": "Pacific Time - Los Angeles",
  "America/Maceio": "Brasilia Standard Time - Maceio",
  "America/Managua": "Central Standard Time - Managua",
  "America/Manaus": "Amazon Standard Time - Manaus",
  "America/Martinique": "Atlantic Standard Time - Martinique",
  "America/Matamoros": "Central Time - Matamoros",
  "America/Mazatlan": "Mexican Pacific Time - Mazatlan",
  "America/Menominee": "Central Time - Menominee",
  "America/Merida": "Central Time - Merida",
  "America/Metlakatla": "Alaska Time - Metlakatla",
  "America/Mexico_City": "Central Time - Mexico City",
  "America/Miquelon": "St. Pierre & Miquelon Time - Miquelon",
  "America/Moncton": "Atlantic Time - Moncton",
  "America/Monterrey": "Central Time - Monterrey",
  "America/Montevideo": "Uruguay Standard Time - Montevideo",
  "America/New_York": "Eastern Time - New York",
  "America/Nipigon": "Eastern Time - Nipigon",
  "America/Nome": "Alaska Time - Nome",
  "America/Noronha": "Fernando de Noronha Standard Time - Noronha",
  "America/North_Dakota/Beulah": "Central Time - Beulah, North Dakota",
  "America/North_Dakota/Center": "Central Time - Center, North Dakota",
  "America/North_Dakota/New_Salem": "Central Time - New Salem, North Dakota",
  "America/Nuuk": "West Greenland Time - Nuuk",
  "America/Ojinaga": "Mountain Time - Ojinaga",
  "America/Panama": "Eastern Standard Time - Panama",
  "America/Pangnirtung": "Eastern Time - Pangnirtung",
  "America/Paramaribo": "Suriname Time - Paramaribo",
  "America/Phoenix": "Mountain Standard Time - Phoenix",
  "America/Port-au-Prince": "Eastern Time - Port-au-Prince",
  "America/Porto_Velho": "Amazon Standard Time - Porto Velho",
  "America/Puerto_Rico": "Atlantic Standard Time - Puerto Rico",
  "America/Punta_Arenas": "Punta Arenas Time - Punta Arenas",
  "America/Rainy_River": "Central Time - Rainy River",
  "America/Rankin_Inlet": "Central Time - Rankin Inlet",
  "America/Recife": "Brasilia Standard Time - Recife",
  "America/Regina": "Central Standard Time - Regina",
  "America/Resolute": "Central Time - Resolute",
  "America/Rio_Branco": "Acre Standard Time - Rio Branco",
  "America/Santarem": "Brasilia Standard Time - Santarem",
  "America/Santiago": "Chile Time - Santiago",
  "America/Santo_Domingo": "Atlantic Standard Time - Santo Domingo",
  "America/Sao_Paulo": "Brasilia Standard Time - Sao Paulo",
  "America/Scoresbysund": "East Greenland Time - Scoresbysund",
  "America/Sitka": "Alaska Time - Sitka",
  "America/St_Johns": "Newfoundland Time - St Johns",
  "America/Swift_Current": "Central Standard Time - Swift Current",
  "America/Tegucigalpa": "Central Standard Time - Tegucigalpa",
  "America/Thule": "Atlantic Time - Thule",
  "America/Thunder_Bay": "Eastern Time - Thunder Bay",
  "America/Tijuana": "Pacific Time - Tijuana",
  "America/Toronto": "Eastern Time - Toronto",
  "America/Vancouver": "Pacific Time - Vancouver",
  "America/Whitehorse": "Mountain Standard Time - Whitehorse",
  "America/Winnipeg": "Central Time - Winnipeg",
  "America/Yakutat": "Alaska Time - Yakutat",
  "America/Yellowknife": "Mountain Time - Yellowknife",
  "Antarctica/Casey": "Casey Time - Casey",
  "Antarctica/Davis": "Davis Time - Davis",
  "Antarctica/Macquarie": "Eastern Australia Time - Macquarie",
  "Antarctica/Mawson": "Mawson Time - Mawson",
  "Antarctica/Palmer": "Palmer Time - Palmer",
  "Antarctica/Rothera": "Rothera Time - Rothera",
  "Antarctica/Troll": "Troll Time - Troll",
  "Antarctica/Vostok": "Vostok Time - Vostok",
  "Asia/Almaty": "East Kazakhstan Time - Almaty",
  "Asia/Amman": "Eastern European Time - Amman",
  "Asia/Anadyr": "Anadyr Standard Time - Anadyr",
  "Asia/Aqtau": "West Kazakhstan Time - Aqtau",
  "Asia/Aqtobe": "West Kazakhstan Time - Aqtobe",
  "Asia/Ashgabat": "Turkmenistan Standard Time - Ashgabat",
  "Asia/Atyrau": "West Kazakhstan Time - Atyrau",
  "Asia/Baghdad": "Arabian Standard Time - Baghdad",
  "Asia/Baku": "Azerbaijan Standard Time - Baku",
  "Asia/Bangkok": "Indochina Time - Bangkok",
  "Asia/Barnaul": "Barnaul Time - Barnaul",
  "Asia/Beirut": "Eastern European Time - Beirut",
  "Asia/Bishkek": "Kyrgyzstan Time - Bishkek",
  "Asia/Brunei": "Brunei Darussalam Time - Brunei",
  "Asia/Chita": "Yakutsk Standard Time - Chita",
  "Asia/Choibalsan": "Ulaanbaatar Standard Time - Choibalsan",
  "Asia/Colombo": "India Standard Time - Colombo",
  "Asia/Damascus": "Eastern European Time - Damascus",
  "Asia/Dhaka": "Bangladesh Standard Time - Dhaka",
  "Asia/Dili": "East Timor Time - Dili",
  "Asia/Dubai": "Gulf Standard Time - Dubai",
  "Asia/Dushanbe": "Tajikistan Time - Dushanbe",
  "Asia/Famagusta": "Famagusta Time - Famagusta",
  "Asia/Gaza": "Eastern European Time - Gaza",
  "Asia/Hebron": "Eastern European Time - Hebron",
  "Asia/Ho_Chi_Minh": "Indochina Time - Ho Chi Minh",
  "Asia/Hong_Kong": "Hong Kong Standard Time - Hong Kong",
  "Asia/Hovd": "Hovd Standard Time - Hovd",
  "Asia/Irkutsk": "Irkutsk Standard Time - Irkutsk",
  "Asia/Jakarta": "Western Indonesia Time - Jakarta",
  "Asia/Jayapura": "Eastern Indonesia Time - Jayapura",
  "Asia/Jerusalem": "Israel Time - Jerusalem",
  "Asia/Kabul": "Afghanistan Time - Kabul",
  "Asia/Kamchatka": "Petropavlovsk-Kamchatski Standard Time - Kamchatka",
  "Asia/Karachi": "Pakistan Standard Time - Karachi",
  "Asia/Kathmandu": "Nepal Time - Kathmandu",
  "Asia/Khandyga": "Yakutsk Standard Time - Khandyga",
  "Asia/Kolkata": "India Standard Time - Kolkata",
  "Asia/Krasnoyarsk": "Krasnoyarsk Standard Time - Krasnoyarsk",
  "Asia/Kuala_Lumpur": "Malaysia Time - Kuala Lumpur",
  "Asia/Kuching": "Malaysia Time - Kuching",
  "Asia/Macau": "China Standard Time - Macau",
  "Asia/Magadan": "Magadan Standard Time - Magadan",
  "Asia/Makassar": "Central Indonesia Time - Makassar",
  "Asia/Manila": "Philippine Standard Time - Manila",
  "Asia/Nicosia": "Eastern European Time - Nicosia",
  "Asia/Novokuznetsk": "Krasnoyarsk Standard Time - Novokuznetsk",
  "Asia/Novosibirsk": "Novosibirsk Standard Time - Novosibirsk",
  "Asia/Omsk": "Omsk Standard Time - Omsk",
  "Asia/Oral": "West Kazakhstan Time - Oral",
  "Asia/Pontianak": "Western Indonesia Time - Pontianak",
  "Asia/Pyongyang": "Korean Standard Time - Pyongyang",
  "Asia/Qatar": "Arabian Standard Time - Qatar",
  "Asia/Qostanay": "East Kazakhstan Time - Qostanay",
  "Asia/Qyzylorda": "West Kazakhstan Time - Qyzylorda",
  "Asia/Riyadh": "Arabian Standard Time - Riyadh",
  "Asia/Sakhalin": "Sakhalin Standard Time - Sakhalin",
  "Asia/Samarkand": "Uzbekistan Standard Time - Samarkand",
  "Asia/Seoul": "Korean Standard Time - Seoul",
  "Asia/Shanghai": "China Standard Time - Shanghai",
  "Asia/Singapore": "Singapore Standard Time - Singapore",
  "Asia/Srednekolymsk": "Srednekolymsk Time - Srednekolymsk",
  "Asia/Taipei": "Taipei Standard Time - Taipei",
  "Asia/Tashkent": "Uzbekistan Standard Time - Tashkent",
  "Asia/Tbilisi": "Georgia Standard Time - Tbilisi",
  "Asia/Tehran": "Iran Time - Tehran",
  "Asia/Thimphu": "Bhutan Time - Thimphu",
  "Asia/Tokyo": "Japan Standard Time - Tokyo",
  "Asia/Tomsk": "Tomsk Time - Tomsk",
  "Asia/Ulaanbaatar": "Ulaanbaatar Standard Time - Ulaanbaatar",
  "Asia/Urumqi": "Urumqi Time - Urumqi",
  "Asia/Ust-Nera": "Vladivostok Standard Time - Ust-Nera",
  "Asia/Vladivostok": "Vladivostok Standard Time - Vladivostok",
  "Asia/Yakutsk": "Yakutsk Standard Time - Yakutsk",
  "Asia/Yangon": "Myanmar Time - Yangon",
  "Asia/Yekaterinburg": "Yekaterinburg Standard Time - Yekaterinburg",
  "Asia/Yerevan": "Armenia Standard Time - Yerevan",
  "Atlantic/Azores": "Azores Time - Azores",
  "Atlantic/Bermuda": "Atlantic Time - Bermuda",
  "Atlantic/Canary": "Western European Time - Canary",
  "Atlantic/Cape_Verde": "Cape Verde Standard Time - Cape Verde",
  "Atlantic/Faroe": "Western European Time - Faroe",
  "Atlantic/Madeira": "Western European Time - Madeira",
  "Atlantic/Reykjavik": "Greenwich Mean Time - Reykjavik",
  "Atlantic/South_Georgia": "South Georgia Time - South Georgia",
  "Atlantic/Stanley": "Falkland Islands Standard Time - Stanley",
  "Australia/Adelaide": "Central Australia Time - Adelaide",
  "Australia/Brisbane": "Australian Eastern Standard Time - Brisbane",
  "Australia/Broken_Hill": "Central Australia Time - Broken Hill",
  "Australia/Darwin": "Australian Central Standard Time - Darwin",
  "Australia/Eucla": "Australian Central Western Standard Time - Eucla",
  "Australia/Hobart": "Eastern Australia Time - Hobart",
  "Australia/Lindeman": "Australian Eastern Standard Time - Lindeman",
  "Australia/Lord_Howe": "Lord Howe Time - Lord Howe",
  "Australia/Melbourne": "Eastern Australia Time - Melbourne",
  "Australia/Perth": "Australian Western Standard Time - Perth",
  "Australia/Sydney": "Eastern Australia Time - Sydney",
  "Europe/Amsterdam": "Central European Time - Amsterdam",
  "Europe/Andorra": "Central European Time - Andorra",
  "Europe/Astrakhan": "Astrakhan Time - Astrakhan",
  "Europe/Athens": "Eastern European Time - Athens",
  "Europe/Belgrade": "Central European Time - Belgrade",
  "Europe/Berlin": "Central European Time - Berlin",
  "Europe/Brussels": "Central European Time - Brussels",
  "Europe/Bucharest": "Eastern European Time - Bucharest",
  "Europe/Budapest": "Central European Time - Budapest",
  "Europe/Chisinau": "Eastern European Time - Chisinau",
  "Europe/Copenhagen": "Central European Time - Copenhagen",
  "Europe/Dublin": "Ireland Time - Dublin",
  "Europe/Gibraltar": "Central European Time - Gibraltar",
  "Europe/Helsinki": "Eastern European Time - Helsinki",
  "Europe/Istanbul": "Turkey Time - Istanbul",
  "Europe/Kaliningrad": "Eastern European Standard Time - Kaliningrad",
  "Europe/Kiev": "Eastern European Time - Kiev",
  "Europe/Kirov": "Kirov Time - Kirov",
  "Europe/Lisbon": "Western European Time - Lisbon",
  "Europe/London": "United Kingdom Time - London",
  "Europe/Luxembourg": "Central European Time - Luxembourg",
  "Europe/Madrid": "Central European Time - Madrid",
  "Europe/Malta": "Central European Time - Malta",
  "Europe/Minsk": "Moscow Standard Time - Minsk",
  "Europe/Monaco": "Central European Time - Monaco",
  "Europe/Moscow": "Moscow Standard Time - Moscow",
  "Europe/Oslo": "Central European Time - Oslo",
  "Europe/Paris": "Central European Time - Paris",
  "Europe/Prague": "Central European Time - Prague",
  "Europe/Riga": "Eastern European Time - Riga",
  "Europe/Rome": "Central European Time - Rome",
  "Europe/Samara": "Samara Standard Time - Samara",
  "Europe/Saratov": "Saratov Time - Saratov",
  "Europe/Simferopol": "Moscow Standard Time - Simferopol",
  "Europe/Sofia": "Eastern European Time - Sofia",
  "Europe/Stockholm": "Central European Time - Stockholm",
  "Europe/Tallinn": "Eastern European Time - Tallinn",
  "Europe/Tirane": "Central European Time - Tirane",
  "Europe/Ulyanovsk": "Ulyanovsk Time - Ulyanovsk",
  "Europe/Uzhgorod": "Eastern European Time - Uzhgorod",
  "Europe/Vienna": "Central European Time - Vienna",
  "Europe/Vilnius": "Eastern European Time - Vilnius",
  "Europe/Volgograd": "Volgograd Standard Time - Volgograd",
  "Europe/Warsaw": "Central European Time - Warsaw",
  "Europe/Zaporozhye": "Eastern European Time - Zaporozhye",
  "Europe/Zurich": "Central European Time - Zurich",
  "Etc/GMT": "GMT",
  "Etc/GMT+1": "GMT -1",
  "Etc/GMT+10": "GMT -10",
  "Etc/GMT+11": "GMT -11",
  "Etc/GMT+12": "GMT -12",
  "Etc/GMT+2": "GMT -2",
  "Etc/GMT+3": "GMT -3",
  "Etc/GMT+4": "GMT -4",
  "Etc/GMT+5": "GMT -5",
  "Etc/GMT+6": "GMT -6",
  "Etc/GMT+7": "GMT -7",
  "Etc/GMT+8": "GMT -8",
  "Etc/GMT+9": "GMT -9",
  "Etc/GMT-1": "GMT +1",
  "Etc/GMT-10": "GMT +10",
  "Etc/GMT-11": "GMT +11",
  "Etc/GMT-12": "GMT +12",
  "Etc/GMT-13": "GMT +13",
  "Etc/GMT-14": "GMT +14",
  "Etc/GMT-2": "GMT +2",
  "Etc/GMT-3": "GMT +3",
  "Etc/GMT-4": "GMT +4",
  "Etc/GMT-5": "GMT +5",
  "Etc/GMT-6": "GMT +6",
  "Etc/GMT-7": "GMT +7",
  "Etc/GMT-8": "GMT +8",
  "Etc/GMT-9": "GMT +9",
  "Indian/Chagos": "Indian Ocean Time - Chagos",
  "Indian/Christmas": "Christmas Island Time - Christmas",
  "Indian/Cocos": "Cocos Islands Time - Cocos",
  "Indian/Kerguelen": "French Southern & Antarctic Time - Kerguelen",
  "Indian/Mahe": "Seychelles Time - Mahe",
  "Indian/Maldives": "Maldives Time - Maldives",
  "Indian/Mauritius": "Mauritius Standard Time - Mauritius",
  "Indian/Reunion": "Réunion Time - Reunion",
  "Pacific/Apia": "Apia Time - Apia",
  "Pacific/Auckland": "New Zealand Time - Auckland",
  "Pacific/Bougainville": "Bougainville Time - Bougainville",
  "Pacific/Chatham": "Chatham Time - Chatham",
  "Pacific/Chuuk": "Chuuk Time - Chuuk",
  "Pacific/Easter": "Easter Island Time - Easter",
  "Pacific/Efate": "Vanuatu Standard Time - Efate",
  "Pacific/Fakaofo": "Tokelau Time - Fakaofo",
  "Pacific/Fiji": "Fiji Time - Fiji",
  "Pacific/Funafuti": "Tuvalu Time - Funafuti",
  "Pacific/Galapagos": "Galapagos Time - Galapagos",
  "Pacific/Gambier": "Gambier Time - Gambier",
  "Pacific/Guadalcanal": "Solomon Islands Time - Guadalcanal",
  "Pacific/Guam": "Chamorro Standard Time - Guam",
  "Pacific/Honolulu": "Hawaii-Aleutian Standard Time - Honolulu",
  "Pacific/Enderbury": "Phoenix Islands Time - Enderbury",
  "Pacific/Kiritimati": "Line Islands Time - Kiritimati",
  "Pacific/Kosrae": "Kosrae Time - Kosrae",
  "Pacific/Kwajalein": "Marshall Islands Time - Kwajalein",
  "Pacific/Majuro": "Marshall Islands Time - Majuro",
  "Pacific/Marquesas": "Marquesas Time - Marquesas",
  "Pacific/Nauru": "Nauru Time - Nauru",
  "Pacific/Niue": "Niue Time - Niue",
  "Pacific/Norfolk": "Norfolk Island Time - Norfolk",
  "Pacific/Noumea": "New Caledonia Standard Time - Noumea",
  "Pacific/Pago_Pago": "Samoa Standard Time - Pago Pago",
  "Pacific/Palau": "Palau Time - Palau",
  "Pacific/Pitcairn": "Pitcairn Time - Pitcairn",
  "Pacific/Pohnpei": "Ponape Time - Pohnpei",
  "Pacific/Port_Moresby": "Papua New Guinea Time - Port Moresby",
  "Pacific/Rarotonga": "Cook Islands Standard Time - Rarotonga",
  "Pacific/Tahiti": "Tahiti Time - Tahiti",
  "Pacific/Tarawa": "Gilbert Islands Time - Tarawa",
  "Pacific/Tongatapu": "Tonga Standard Time - Tongatapu",
  "Pacific/Wake": "Wake Island Time - Wake",
  "Pacific/Wallis": "Wallis & Futuna Time - Wallis",
  UTC: "Universal Coordinated Time",
};

// Pulled from IANA database (and then some manual tagging of existing data)
// https://github.com/rogierschouten/tzdata-generate/blob/master/dist/tzdata/timezone-data.json
export const TZ_ALIAS_TO_IANA: Record<string, TimezoneIana> = {
  "Africa/Accra": "Africa/Abidjan",
  "Africa/Addis_Ababa": "Africa/Nairobi",
  "Africa/Asmara": "Africa/Nairobi",
  "Africa/Asmera": "Africa/Nairobi",
  "Africa/Bamako": "Africa/Abidjan",
  "Africa/Bangui": "Africa/Lagos",
  "Africa/Banjul": "Africa/Abidjan",
  "Africa/Blantyre": "Africa/Maputo",
  "Africa/Brazzaville": "Africa/Lagos",
  "Africa/Bujumbura": "Africa/Maputo",
  "Africa/Conakry": "Africa/Abidjan",
  "Africa/Dakar": "Africa/Abidjan",
  "Africa/Dar_es_Salaam": "Africa/Nairobi",
  "Africa/Djibouti": "Africa/Nairobi",
  "Africa/Douala": "Africa/Lagos",
  "Africa/Freetown": "Africa/Abidjan",
  "Africa/Gaborone": "Africa/Maputo",
  "Africa/Harare": "Africa/Maputo",
  "Africa/Kampala": "Africa/Nairobi",
  "Africa/Kigali": "Africa/Maputo",
  "Africa/Kinshasa": "Africa/Lagos",
  "Africa/Libreville": "Africa/Lagos",
  "Africa/Lome": "Africa/Abidjan",
  "Africa/Luanda": "Africa/Lagos",
  "Africa/Lubumbashi": "Africa/Maputo",
  "Africa/Lusaka": "Africa/Maputo",
  "Africa/Malabo": "Africa/Lagos",
  "Africa/Maseru": "Africa/Johannesburg",
  "Africa/Mbabane": "Africa/Johannesburg",
  "Africa/Mogadishu": "Africa/Nairobi",
  "Africa/Niamey": "Africa/Lagos",
  "Africa/Nouakchott": "Africa/Abidjan",
  "Africa/Ouagadougou": "Africa/Abidjan",
  "Africa/Porto-Novo": "Africa/Lagos",
  "Africa/Timbuktu": "Africa/Abidjan",
  "America/Anguilla": "America/Puerto_Rico",
  "America/Antigua": "America/Puerto_Rico",
  "America/Argentina/ComodRivadavia": "America/Argentina/Catamarca",
  "America/Aruba": "America/Puerto_Rico",
  "America/Atikokan": "America/Panama",
  "America/Atka": "America/Adak",
  "America/Blanc-Sablon": "America/Puerto_Rico",
  "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
  "America/Catamarca": "America/Argentina/Catamarca",
  "America/Cayman": "America/Panama",
  "America/Coral_Harbour": "America/Panama",
  "America/Cordoba": "America/Argentina/Cordoba",
  "America/Creston": "America/Phoenix",
  "America/Curacao": "America/Puerto_Rico",
  "America/Dominica": "America/Puerto_Rico",
  "America/Ensenada": "America/Tijuana",
  "America/Fort_Wayne": "America/Indiana/Indianapolis",
  "America/Godthab": "America/Nuuk",
  "America/Grenada": "America/Puerto_Rico",
  "America/Guadeloupe": "America/Puerto_Rico",
  "America/Indianapolis": "America/Indiana/Indianapolis",
  "America/Jujuy": "America/Argentina/Jujuy",
  "America/Knox_IN": "America/Indiana/Knox",
  "America/Kralendijk": "America/Puerto_Rico",
  "America/Louisville": "America/Kentucky/Louisville",
  "America/Lower_Princes": "America/Puerto_Rico",
  "America/Marigot": "America/Puerto_Rico",
  "America/Mendoza": "America/Argentina/Mendoza",
  "America/Montreal": "America/Toronto",
  "America/Montserrat": "America/Puerto_Rico",
  "America/Nassau": "America/Toronto",
  "America/Port_of_Spain": "America/Puerto_Rico",
  "America/Porto_Acre": "America/Rio_Branco",
  "America/Rosario": "America/Argentina/Cordoba",
  "America/Santa_Isabel": "America/Tijuana",
  "America/Shiprock": "America/Denver",
  "America/St_Barthelemy": "America/Puerto_Rico",
  "America/St_Kitts": "America/Puerto_Rico",
  "America/St_Lucia": "America/Puerto_Rico",
  "America/St_Thomas": "America/Puerto_Rico",
  "America/St_Vincent": "America/Puerto_Rico",
  "America/Tortola": "America/Puerto_Rico",
  "America/Virgin": "America/Puerto_Rico",
  "Antarctica/DumontDUrville": "Pacific/Port_Moresby",
  "Antarctica/McMurdo": "Pacific/Auckland",
  "Antarctica/South_Pole": "Pacific/Auckland",
  "Antarctica/Syowa": "Asia/Riyadh",
  "Arctic/Longyearbyen": "Europe/Oslo",
  "Argentina Standard Time": "America/Argentina/Buenos_Aires",
  "Asia/Aden": "Asia/Riyadh",
  "Asia/Ashkhabad": "Asia/Ashgabat",
  "Asia/Bahrain": "Asia/Qatar",
  "Asia/Calcutta": "Asia/Kolkata",
  "Asia/Chongqing": "Asia/Shanghai",
  "Asia/Chungking": "Asia/Shanghai",
  "Asia/Dacca": "Asia/Dhaka",
  "Asia/Harbin": "Asia/Shanghai",
  "Asia/Istanbul": "Europe/Istanbul",
  "Asia/Kashgar": "Asia/Urumqi",
  "Asia/Katmandu": "Asia/Kathmandu",
  "Asia/Kuwait": "Asia/Riyadh",
  "Asia/Macao": "Asia/Macau",
  "Asia/Muscat": "Asia/Dubai",
  "Asia/Phnom_Penh": "Asia/Bangkok",
  "Asia/Rangoon": "Asia/Yangon",
  "Asia/Saigon": "Asia/Ho_Chi_Minh",
  "Asia/Tel_Aviv": "Asia/Jerusalem",
  "Asia/Thimbu": "Asia/Thimphu",
  "Asia/Ujung_Pandang": "Asia/Makassar",
  "Asia/Ulan_Bator": "Asia/Ulaanbaatar",
  "Asia/Vientiane": "Asia/Bangkok",
  "Atlantic Standard Time": "America/New_York",
  "Atlantic/Faeroe": "Atlantic/Faroe",
  "Atlantic/Jan_Mayen": "Europe/Oslo",
  "Atlantic/St_Helena": "Africa/Abidjan",
  "Australia/ACT": "Australia/Sydney",
  "Australia/Canberra": "Australia/Sydney",
  "Australia/Currie": "Australia/Hobart",
  "Australia/LHI": "Australia/Lord_Howe",
  "Australia/North": "Australia/Darwin",
  "Australia/NSW": "Australia/Sydney",
  "Australia/Queensland": "Australia/Brisbane",
  "Australia/South": "Australia/Adelaide",
  "Australia/Tasmania": "Australia/Hobart",
  "Australia/Victoria": "Australia/Melbourne",
  "Australia/West": "Australia/Perth",
  "Australia/Yancowinna": "Australia/Broken_Hill",
  "Australian Eastern Daylight Time": "Australia/Melbourne",
  "Australian Eastern Standard Time": "Australia/Melbourne",
  "Bangladesh Standard Time": "Asia/Dhaka",
  "Brasilia Standard Time": "America/Sao_Paulo",
  "Brazil/Acre": "America/Rio_Branco",
  "Brazil/DeNoronha": "America/Noronha",
  "Brazil/East": "America/Sao_Paulo",
  "Brazil/West": "America/Manaus",
  "British Summer Time": "Europe/London",
  "Canada/Atlantic": "America/Halifax",
  "Canada/Central": "America/Winnipeg",
  "Canada/Eastern": "America/Toronto",
  "Canada/Mountain": "America/Edmonton",
  "Canada/Newfoundland": "America/St_Johns",
  "Canada/Pacific": "America/Vancouver",
  "Canada/Saskatchewan": "America/Regina",
  "Canada/Yukon": "America/Whitehorse",
  "Central Daylight Time": "America/Chicago",
  "Central European Summer Time": "Europe/Paris",
  "Central Standard Time": "America/Chicago",
  "centraleuropeisk sommartid": "Europe/Paris",
  "Chamorro Standard Time": "Pacific/Guam",
  "Chile/Continental": "America/Santiago",
  "Chile/EasterIsland": "Pacific/Easter",
  "China Standard Time": "Asia/Shanghai",
  "Colombia Standard Time": "America/Bogota",
  "East Africa Time": "Africa/Nairobi",
  "Eastern Daylight Time": "America/New_York",
  "Eastern European Summer Time": "Europe/Athens",
  "Etc/GMT+0": "Etc/GMT",
  "Etc/GMT-0": "Etc/GMT",
  "Etc/GMT0": "Etc/GMT",
  "Etc/Greenwich": "Etc/GMT",
  "Etc/UCT": "Etc/GMT",
  "Etc/Universal": "Etc/GMT",
  "Etc/Zulu": "Etc/GMT",
  "Europe/Belfast": "Europe/London",
  "Europe/Bratislava": "Europe/Prague",
  "Europe/Busingen": "Europe/Zurich",
  "Europe/Guernsey": "Europe/London",
  "Europe/Isle_of_Man": "Europe/London",
  "Europe/Jersey": "Europe/London",
  "Europe/Ljubljana": "Europe/Belgrade",
  "Europe/Mariehamn": "Europe/Helsinki",
  "Europe/Nicosia": "Asia/Nicosia",
  "Europe/Podgorica": "Europe/Belgrade",
  "Europe/San_Marino": "Europe/Rome",
  "Europe/Sarajevo": "Europe/Belgrade",
  "Europe/Skopje": "Europe/Belgrade",
  "Europe/Tiraspol": "Europe/Chisinau",
  "Europe/Vaduz": "Europe/Zurich",
  "Europe/Vatican": "Europe/Rome",
  "Europe/Zagreb": "Europe/Belgrade",
  "GB-Eire": "Europe/London",
  "GMT+0": "Etc/GMT",
  "GMT+00:00": "Etc/GMT",
  "GMT+03:00": "Etc/GMT+3",
  "GMT-0": "Etc/GMT",
  "Greenwich Mean Time": "Etc/GMT",
  "Hawaii-Aleutian Standard Time": "America/Anchorage",
  "heure d’été de l’Est": "America/New_York",
  "heure d’été des Rocheuses": "America/Denver",
  "heure d’été d’Europe centrale": "Europe/Paris",
  "heure normale d’Europe centrale": "Europe/Paris",
  "hora de Bolivia": "America/New_York",
  "hora de Ecuador": "America/Guayaquil",
  "hora de Venezuela": "America/Caracas",
  "hora de verano central": "America/Chicago",
  "hora de verano de Chile": "America/Santiago",
  "hora de verano de Europa central": "Europe/Paris",
  "hora de verano de Europa occidental": "Europe/Athens",
  "hora estándar central": "America/Chicago",
  "hora estándar de Argentina": "America/Argentina/Buenos_Aires",
  "hora estándar de Colombia": "America/Bogota",
  "hora estándar del Atlántico": "America/New_York",
  "hora estándar oriental": "America/Los_Angeles",
  "India Standard Time": "Asia/Kolkata",
  "Indian/Antananarivo": "Africa/Nairobi",
  "Indian/Comoro": "Africa/Nairobi",
  "Indian/Mayotte": "Africa/Nairobi",
  "Irish Standard Time": "Europe/Dublin",
  "Israel Daylight Time": "Asia/Jerusalem",
  "Malaysia Time": "Asia/Kuala_Lumpur",
  "Mexico/BajaNorte": "America/Tijuana",
  "Mexico/BajaSur": "America/Mazatlan",
  "Mexico/General": "America/Mexico_City",
  "Midden-Europese zomertijd": "Asia/Riyadh",
  "Mitteleuropäische Sommerzeit": "Europe/Berlin",
  "Mountain Daylight Time": "America/Denver",
  "Mountain Standard Time": "America/Denver",
  "New Zealand Daylight Time": "Pacific/Auckland",
  "NZ-CHAT": "Pacific/Chatham",
  "Ora legale dell’Europa centrale": "Europe/Paris",
  "Pacific Daylight Time": "America/Los_Angeles",
  "Pacific/Johnston": "Pacific/Honolulu",
  "Pacific/Midway": "Pacific/Pago_Pago",
  "Pacific/Ponape": "Pacific/Pohnpei",
  "Pacific/Saipan": "Pacific/Guam",
  "Pacific/Samoa": "Pacific/Pago_Pago",
  "Pacific/Truk": "Pacific/Chuuk",
  "Pacific/Yap": "Pacific/Chuuk",
  "Philippine Standard Time": "Asia/Manila",
  "Singapore Standard Time": "Asia/Singapore",
  "South Africa Standard Time": "Africa/Johannesburg",
  "US/Alaska": "America/Anchorage",
  "US/Aleutian": "America/Adak",
  "US/Arizona": "America/Phoenix",
  "US/Central": "America/Chicago",
  "US/East-Indiana": "America/Indiana/Indianapolis",
  "US/Eastern": "America/New_York",
  "US/Hawaii": "Pacific/Honolulu",
  "US/Indiana-Starke": "America/Indiana/Knox",
  "US/Michigan": "America/Detroit",
  "US/Mountain": "America/Denver",
  "US/Pacific": "America/Los_Angeles",
  "US/Samoa": "Pacific/Pago_Pago",
  "W-SU": "Europe/Moscow",
  "West Africa Standard Time": "Africa/Algiers",
  "Western Indonesia Time": "Asia/Jakarta",
  "שעון ישראל (קיץ)": "Asia/Jerusalem",
  "대한민국 표준시": "Asia/Seoul",
  Cuba: "America/Havana",
  Egypt: "Africa/Cairo",
  Eire: "Europe/Dublin",
  en: "America/Los_Angeles",
  GB: "Europe/London",
  GMT0: "Etc/GMT",
  GMT: "Etc/GMT",
  Greenwich: "Etc/GMT",
  Hongkong: "Asia/Hong_Kong",
  Iceland: "Atlantic/Reykjavik",
  Iran: "Asia/Tehran",
  Israel: "Asia/Jerusalem",
  Jamaica: "America/Jamaica",
  Japan: "Asia/Tokyo",
  Kwajalein: "Pacific/Kwajalein",
  Libya: "Africa/Tripoli",
  Navajo: "America/Denver",
  NZ: "Pacific/Auckland",
  Poland: "Europe/Warsaw",
  Portugal: "Europe/Lisbon",
  PRC: "Asia/Shanghai",
  ROC: "Asia/Taipei",
  ROK: "Asia/Seoul",
  Singapore: "Asia/Singapore",
  Turkey: "Europe/Istanbul",
  Universal: "Etc/GMT",
  UTC: "Etc/GMT",
  Zulu: "Etc/GMT",
};

export type TimezoneIana = typeof TIMEZONES[number];

/**
 * Formatted like America/Los_Angeles.
 *
 * We hope that this returns a timezone is in the Iana TZ database.
 */
export const getTimezoneIana = (): TimezoneIana | null => {
  const dateTimeFormat = new Intl.DateTimeFormat("default", {});

  if (!dateTimeFormat.resolvedOptions) {
    return null;
  }

  const timezoneStr = dateTimeFormat.resolvedOptions().timeZone;

  if (TIMEZONES.includes(timezoneStr as any)) {
    return timezoneStr as TimezoneIana;
  }

  if (timezoneStr in TZ_ALIAS_TO_IANA) {
    return TZ_ALIAS_TO_IANA[timezoneStr];
  }

  return null;
};
