name: Test Anchor Program

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_js_tests:
    name: Anchor Tests
    runs-on: ubuntu-20.04
    container: projectserum/build:v0.24.2

    steps:
      - uses: actions/checkout@v3
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Set default toolchain
        run: rustup default stable
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Generate new keygen
        run: solana-keygen new
      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899
      - name: Check solana config
        run: solana config get
      - name: Install yarn dependencies
        run: npm install pnpm -g && pnpm install
      - name: Build
        run: anchor build
      - name: Lint
        run: pnpm run lint
      - name: Typescript Compile (tsc)
        run: pnpm run tsc
      - name: Run tests
        run: anchor test
